### ISSUE TITLE
Doesn't seem to build?

### ISSUE THREAD

**Issue by eriksank** [jkalbhenn/scrypt#1]
Interesting tool! I've run into a snag, though:

```
$ sudo exec/make+install.sh 
/tmp/ccspfJx5.o: In function `main':
cli.c:(.text.startup+0x189): undefined reference to `scrypt_parse_string_crypt'
cli.c:(.text.startup+0x1ca): undefined reference to `scrypt_to_string_crypt'
cli.c:(.text.startup+0x27a): undefined reference to `scrypt_strerror'
cli.c:(.text.startup+0x2cb): undefined reference to `scrypt_parse_string_base91'
cli.c:(.text.startup+0x30b): undefined reference to `scrypt_to_string_base91'
cli.c:(.text.startup+0x3bc): undefined reference to `scrypt_to_string_crypt'
cli.c:(.text.startup+0x410): undefined reference to `scrypt_to_string_base91'
collect2: error: ld returned 1 exit status
install: cannot stat ‘temp/scrypt-kdf’: No such file or directory
```
It looks like a linker error. Any idea why? You do not mention any dependencies that should be installed first. Furthermore, the symbols "scrypt_ ..." all seem to be internal ones. It looks like the main program cannot find symbols that should be defined:

```
$ nm temp/libscrypt.so
...
0000000000005e40 T scrypt_parse_string_base91
0000000000006590 T scrypt_parse_string_crypt
0000000000005c20 T scrypt_set_defaults
0000000000005950 T scrypt_strerror
```
The library is correctly installed too:
```
$ ls -lh /usr/lib | grep scrypt
-rw-r--r--  1 root root      38K Sep 12 13:04 libscrypt.so
```
To it is a mystery why `gcc` refuses to link with `libscrypt.so`.
```
gcc -O3 -std=c11 -lscrypt source/cli.c -o temp/$n && chmod 755 temp/$n
```
This instruction fails on  the part that says `-lscrypt`. I've tried adding `-L/usr/lib`, which is -- I know -- ridiculous, but then again, it did not help either. I've tried with another prefix and it does not work either. I suspect that you have built it with an older version of gcc. Mine is:

$ gcc -v
gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13) 

It is a gcc linking issue, but I am not familiar enough with how gcc may have changed the rules in the meanwhile.

**Comment by jkalbhenn** [comment]
sorry for not responding sooner. i got no notification - githubs notification messages seem to bounce at my email providers spam filter.

what i can say at the moment:
* as far as i know there are no other dependencies except for what is already installed with gcc
* the error does not appear on my system. currently i am using gcc version 5.2.0
* if "gcc -O3 -std=c11 -lscrypt source/cli.c -o temp/scrypt-kdf" succeeds and "nm /usr/lib/libscrypt.so" shows the symbols, i do not see yet why the error should occur, especially if the linker paths are set up and files are accessible
* i would guess "./exec/test.sh" shows the same problem
* maybe "ldconfig -v" or "gcc -print-search-dirs" can be of any use

i removed the shared library version script ("-Wl,--version-script=other/export") from the compilation script, i doubt it makes a difference though.

i may try to compile the program on different machines to see if i can reproduce this problem somewhere.

**Comment by jkalbhenn** [comment]
project has been generally updated and the compilation scripts have been mostly rewritten. please re-open/re-create issue if problem persists.
