### ISSUE TITLE
compile fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by AntonLydike** [jkalbhenn/scrypt#2]
When running sudo ./exe/compile, I get the following error (german; translation below)

    user@hostname:~/tmp/scrypt-console$ sudo ./exe/compile
    /tmp/cct3AZVI.o: In Funktion `main':
    cli.c:(.text.startup+0x189): Nicht definierter Verweis auf `scrypt_parse_string_crypt'
    cli.c:(.text.startup+0x1ca): Nicht definierter Verweis auf `scrypt_to_string_crypt'
    cli.c:(.text.startup+0x277): Nicht definierter Verweis auf `scrypt_strerror'
    cli.c:(.text.startup+0x2c8): Nicht definierter Verweis auf `scrypt_parse_string_base91'
    cli.c:(.text.startup+0x308): Nicht definierter Verweis auf `scrypt_to_string_base91'
    cli.c:(.text.startup+0x3bf): Nicht definierter Verweis auf `scrypt_to_string_crypt'
    cli.c:(.text.startup+0x413): Nicht definierter Verweis auf `scrypt_to_string_base91'
    collect2: error: ld returned 1 exit status

Which roughly translates to:

    user@hostname:~/tmp/scrypt-console$ sudo ./exe/compile
    /tmp/cct3AZVI.o: in function `main':
    cli.c:(.text.startup+0x189): undefined reference to `scrypt_parse_string_crypt'
    cli.c:(.text.startup+0x1ca): undefined reference to `scrypt_to_string_crypt'
    cli.c:(.text.startup+0x277): undefined reference to `scrypt_strerror'
    cli.c:(.text.startup+0x2c8): undefined reference to `scrypt_parse_string_base91'
    cli.c:(.text.startup+0x308): undefined reference to `scrypt_to_string_base91'
    cli.c:(.text.startup+0x3bf): undefined reference to `scrypt_to_string_crypt'
    cli.c:(.text.startup+0x413): undefined reference to `scrypt_to_string_base91'
    collect2: error: ld returned 1 exit status

**Comment by jkalbhenn** [comment]
interesting. it looks like building the shared library (./temp/libscrypt.so) succeeds, but it then fails to compile the executable because the shared library file it finds is not valid.

i see you are using sudo, but maybe check the permissions of the files in the directory anyway. maybe reset them to something your normal user can access and try without sudo. because this error message can appear if the library file exists under temp/ but can not be read.

my next guess would be checking the library with "nm -D temp/libscrypt.so", just to see if it exports the functions.

i will look into it further and can also test it on an ubuntu 16.04 tomorrow.

**Comment by AntonLydike** [comment]
Okay. After `$ sudo chmod +x exe/*` I still got the same error (I deleted temp manually before trying).

`nm -D temp/libscrypt.so` prints:

                     U abort
                     U __assert_fail
    0000000000006880 T base91_decode
    0000000000004c70 T basE91_decode
    0000000000004d30 T basE91_decode_end
    0000000000004b10 T basE91_encode
    0000000000004bd0 T basE91_encode_end
    0000000000004af0 T basE91_init
    0000000000209288 B __bss_start
                     U ceil
                     U clock_getres
                     U clock_gettime
    0000000000006200 T crypto_scrypt
    00000000000020d0 T crypto_scrypt_smix
                     U __cxa_atexit
                     w __cxa_finalize
    0000000000007d80 R dectab
    0000000000209288 D _edata
    0000000000007e80 R enctab
    00000000002092b0 B _end
                     U __errno_location
                     U fclose
    0000000000007bcc T _fini
                     U fopen
                     U __fprintf_chk
                     U fputc
                     U fputs
                     U fread
                     U free
                     U fwrite
                     U getrlimit
                     w __gmon_start__
    00000000000016e8 T _init
    0000000000209280 D insecure_memzero_ptr
                     w _ITM_deregisterTMCloneTable
                     w _ITM_registerTMCloneTable
                     w _Jv_RegisterClasses
    0000000000005880 T libcperciva_HMAC_SHA256_Buf
    0000000000005800 T libcperciva_HMAC_SHA256_Final
    0000000000005200 T libcperciva_HMAC_SHA256_Init
    00000000000057f0 T libcperciva_HMAC_SHA256_Update
    0000000000005190 T libcperciva_SHA256_Buf
    0000000000004fd0 T libcperciva_SHA256_Final
    0000000000004d70 T libcperciva_SHA256_Init
    0000000000004db0 T libcperciva_SHA256_Update
    0000000000005fb0 T libcperciva_warn
    00000000000060e0 T libcperciva_warnx
                     U log2f
                     U malloc
                     U memcmp
                     U memcpy
    0000000000006380 T memtouse
                     U mmap
                     U munmap
    0000000000005900 T PBKDF2_SHA256
                     U posix_memalign
    0000000000006910 T random_string
    00000000000068e0 T scrypt
    0000000000006630 T scryptenc_cpuperf
    0000000000006ba0 T scrypt_parse_string_base91
    0000000000007320 T scrypt_parse_string_crypt
    0000000000006980 T scrypt_set_defaults
    00000000000068f0 T scrypt_strerror
    0000000000006dd0 T scrypt_to_string_base91
    0000000000007570 T scrypt_to_string_crypt
                     U __stack_chk_fail
                     U stderr
                     U strchr
                     U __strdup
                     U strerror
                     U strlen
                     U sysconf
                     U sysinfo
                     U __tls_get_addr
                     U __vfprintf_chk
    0000000000005f40 T warnp_setprogname

I am not sure what you meant with 

> reset them to something your normal user can access and try without sudo

Isn't that so by default (I just tried sudo, since I got an error without sudo ¯\\_(ツ)_/¯)
anyway, I get the same error without sudo.

**Comment by jkalbhenn** [comment]
ok, thanks.
so it really looks like the library compiled fine and should be valid.

"gcc -O3 --std=c11 -L./temp -lscrypt source/cli.c -o temp/scrypt-kdf" is the line that seems to be failing.

> reset them to something your normal user can access and try without sudo

i meant setting the permissions of all the files in the scrypt-console folder to something like "chmod 755 -R *" and then executing "./exe/compile" without sudo. but deleting temp is about the same and should be enough.

now the only thing i can currently think of is unpacking the archive (or cloning) again and trying from scratch, but you probably already did that. so i will test it on ubuntu tomorrow and see if i can reproduce it..

**Comment by jkalbhenn** [comment]
adding `-Wl,--no-as-needed -lm` in exe/compile after $gcc to the line in compile_scrypt_kdf() should work.
so that i looks like this: `exit_on_error $gcc -Wl,--no-as-needed -lm --std=c11 -L./temp -lscrypt source/cli.c -o temp/scrypt-kdf`

it seems to be because ubuntu maintainers customized the default gcc and the differences lead to this error. i am going to update the code with a fix soon.
